<a href="https://colab.research.google.com/github/leaf7823/hosripo/blob/master/NumPy_%E5%85%A5%E9%96%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# [2]:ベクトルの定義
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [0]:
# [3]:

a.shape

(3,)

In [0]:
# [4]:
a.ndim

1

In [0]:
# [5]:
# 行列の定義
b = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# [6]:
print('Shape:', b.shape)
print('Rank:', b.ndim)

Shape: (3, 3)
Rank: 2


In [0]:
# [7]:
b.size

9

In [0]:
# [8]:
# 形を指定して、要素が全て 0 で埋められた ndarray を作る
a = np.zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
# [9]:
# 形を指定して、要素が全て 1 で埋められた ndarray を作る
b = np.ones((2, 3))

b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# [10]:
# 形と値を指定して、要素が指定した値で埋められた ndarray を作る
c = np.full((3, 2), 9)

c

array([[9, 9],
       [9, 9],
       [9, 9]])

In [0]:
# [11]:
# 指定された大きさの単位行列を表す ndarray を作る
d = np.eye(5)

d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
# [12]:
# 形を指定して、 0 ~ 1 の間の乱数で要素を埋めた ndarray を作る
e = np.random.random((4, 5))

print(e)
print('Shape:', e.shape)
print('Rank:', e.ndim)
print('size:', e.size)

[[0.31684291 0.84613127 0.35070521 0.39080165 0.14926569]
 [0.19442674 0.70356368 0.39576276 0.2666541  0.46689657]
 [0.56209184 0.09267139 0.3854256  0.44535595 0.88455684]
 [0.32382415 0.98893484 0.69004092 0.96168671 0.54608931]]
Shape: (4, 5)
Rank: 2
size: 20


In [0]:
# [13]:
# 3 から始まり 10 になるまで 1 ずつ増加する数列を作る（10 は含まない）
f = np.arange(3, 10, 1)

f

array([3, 4, 5, 6, 7, 8, 9])

In [0]:
# [14]:
val = e[0, 1]

val

0.5576839292186136

In [0]:
# [15]:
# 4 x 5 行列 e の真ん中の 2 x 3 = 6 個の値を取り出す
center = e[0:2,1:2]

center

array([[0.84613127],
       [0.70356368]])

In [0]:
# 16]:
print('Shape of e:', e.shape)
print('Shape of center:', center.shape)

Shape of e: (4, 5)
Shape of center: (2, 3)


In [0]:
# [17]:

In [0]:
# [18]:

In [0]:
# [19]:

In [0]:
# [20]:

In [0]:
# [21]:

In [0]:
# [22]:

In [0]:
# [23]:

In [0]:
# [24]:

In [0]:
# [25]:

In [0]:
# [26]:

In [0]:
# [27]:

In [0]:
# [28]:

In [0]:
# [29]:

In [0]:
# [30]:

In [0]:
# [31]:

In [0]:
# [32]:

In [0]:
# [33]:

In [0]:
# [34]:

In [0]:
# [35]:

In [0]:
# [36]:

In [0]:
# [37]:

In [0]:
# [38]:

In [0]:
# [39]:

In [0]:
# [40]:

In [0]:
# [41]:

In [0]:
# [42]:

In [0]:
# [43]:

In [0]:
# [44]:

In [0]:
# [45]:

In [0]:
# [46]:

In [0]:
# [47]:

In [0]:
# [48]:

In [0]:
# [49]:

In [0]:
# [50]:

In [0]:
# [51]:

In [0]:
# [52]:

In [0]:
# [53]:

In [0]:
# [54]:

In [0]:
# [55]:

In [0]:
# [56]:

In [0]:
# [57]:

In [0]:
# [58]:

In [0]:
# [59]:

In [0]:
# [60]:

In [0]:
# [61]:

In [0]:
# [62]:

In [0]:
# [63]:

In [0]:
# [64]:

In [0]:
# [65]:

In [0]:
# [66]:

In [0]:
# [67]:

In [0]:
# [68]: