<a href="https://colab.research.google.com/github/leaf7823/hosripo/blob/master/%E3%82%B9%E3%83%A9%E3%82%A4%E3%82%B9%E3%81%AE%E3%81%8A%E5%8B%89%E5%BC%B7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])

In [0]:
array1[4]

5

In [0]:
array1[0] = 10
array1

array([10,  2,  3,  4,  5])

In [0]:
import numpy as np
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
array2[0, 0] # 一行目の一列目

1

In [0]:
array2[1, 0] # 二行目の一列目

4

In [0]:
array2[1, 1] #二行目の二列目

5

In [0]:
print(X[1:3,0:2])


[[ 5  6]
 [10 11]]


In [0]:
X = np.arange(25).reshape(5,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
print(X[2:5,1:4])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [0]:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [0]:
import numpy as np
b = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]
)


print("shape: ",b.shape)
print("Rank : ",b.ndim)
print("size : ",b.size)
b

shape:  (4, 5)
Rank :  2
size :  20


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [0]:
val = b[2:3,2:3]
val

array([[13]])

In [0]:
c = b[0:2,3:5]

c

array([[ 4,  5],
       [ 9, 10]])

In [0]:
a = [1, 2, 3, 4, 5]
print(a[0: 4])
print(a[: 4])
print(a[-3:])
print(a[2: -1])

[1, 2, 3, 4]
[1, 2, 3, 4]
[3, 4, 5]
[3, 4]


In [0]:
a = [1, 2, 3, 4, 5]
print(a[:: 2])
print(a[1:: 2])
print(a[::-1])
print(a[1::-1])

[1, 3, 5]
[2, 4]
[5, 4, 3, 2, 1]
[2, 1]


In [0]:
colorlist = ["Blue", "Red", "Green", "White", "Black"]

print(colorlist[1:3])
print(colorlist[2:3])

['Red', 'Green']
['Green']


In [0]:
e = np.random.random((4, 5))
e
#print('Shape:', e.shape)
#print('Rank:', e.ndim)
#print('size:', e.size)


array([[0.5456703 , 0.53384595, 0.08846361, 0.4447016 , 0.05409587],
       [0.13520422, 0.25870033, 0.54408009, 0.01258047, 0.71193371],
       [0.33350958, 0.06118612, 0.31230561, 0.38586773, 0.67013582],
       [0.6843474 , 0.99997983, 0.94293412, 0.64680994, 0.2019049 ]])

In [0]:
z = e[1:4]
z

array([[0.13520422, 0.25870033, 0.54408009, 0.01258047, 0.71193371],
       [0.33350958, 0.06118612, 0.31230561, 0.38586773, 0.67013582],
       [0.6843474 , 0.99997983, 0.94293412, 0.64680994, 0.2019049 ]])

In [0]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [0]:
print(a[0:4, 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [0]:
# スライスのお勉強　一次
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [0]:
a[2:8:2]

array([2, 4, 6])

In [0]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [0]:
a[:3]

array([0, 1, 2])

In [0]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [0]:
a[:3],a[3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [0]:
a[::2]

array([0, 2, 4, 6, 8])

In [0]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b = np.arange(12).reshape(3,4) # 4×5の二次元配列
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b[1:2]


array([[4, 5, 6, 7]])

In [0]:
b[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])