<a href="https://colab.research.google.com/github/leaf7823/hosripo/blob/master/%E4%BA%8C%E6%AC%A1%E5%85%83%E9%85%8D%E5%88%97%E3%81%AE%E3%82%B9%E3%83%A9%E3%82%A4%E3%82%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
print(array[1:2,0:3])

[[4 5 6]]


In [0]:
array[2]

array([7, 8, 9])

In [0]:
array[:, 2]

array([3, 6, 9])

In [0]:
array[0, 1]

2

In [0]:
  array[:, 1:] # 全ての行の 2 列目以降

array([[2, 3],
       [5, 6],
       [8, 9]])

In [0]:
# # 2 行目以降　の 2 列目以降
array[1:, 1:]
#array[1:3,1:4]

array([[5, 6],
       [8, 9]])

In [0]:
# # 2 行目以降　の 2 列目以降
#array[1:, 1:]
array[1:3,1:5]

array([[5, 6],
       [8, 9]])

In [0]:
array[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])